In [2]:
import numpy as np
array = np.array([1,2,3])

In [4]:
print(array)

[1 2 3]


In [3]:
mean = np.mean(array)

In [5]:
print(mean)

2.0


In [8]:
median = np.median(array)

In [9]:
print(median)

2.0


In [10]:
std_dev = np.std(array)

In [11]:
print(std_dev)

0.816496580927726


In [13]:
total = np.sum(array)

In [14]:
print(total)

6


In [15]:
reshaped_array = array.reshape((3,1))

In [16]:
print(reshaped_array)

[[1]
 [2]
 [3]]


In [19]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concatenated = np.concatenate((array1, array2))

In [20]:
print(concatenated)

[1 2 3 4 5 6]


In [21]:
numbers = np.linspace(0,10,5)

In [22]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
range_array = np.arange(0,10,2)

In [24]:
print(range_array)

[0 2 4 6 8]
